<?php
if( function_exists('register_field_group') ):

register_field_group(array (
	'key' => 'group_54c4772c6e6f6',
	'title' => 'Sub-Menus',
	'fields' => array (
		array (
			'key' => 'field_54da7526bd81f',
			'label' => 'Secondary',
			'name' => 'secondary',
			'prefix' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
		),
		array (
			'key' => 'field_54c477353dfb7',
			'label' => 'Secondary Menu',
			'name' => 'secondary_menu',
			'prefix' => '',
			'type' => 'nav_menu',
			'instructions' => 'This is the menu under the main image.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'save_format' => 'menu',
			'container' => 'nav',
			'allow_null' => 1,
		),
		array (
			'key' => 'field_54da7559bd821',
			'label' => 'Type',
			'name' => 'secondary_type',
			'prefix' => '',
			'type' => 'radio',
			'instructions' => 'Type of Navigation',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'tab' => 'Tab',
				'pill' => 'Pill',
			),
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => '',
			'layout' => 'vertical',
		),
		array (
			'key' => 'field_54da753dbd820',
			'label' => 'Tertiary',
			'name' => 'tertiary',
			'prefix' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
		),
		array (
			'key' => 'field_54c47e5703196',
			'label' => 'Tertiary Title',
			'name' => 'tertiary_menu_title',
			'prefix' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_54c4798d5b2c2',
			'label' => 'Tertiary Menu',
			'name' => 'tertiary_menu',
			'prefix' => '',
			'type' => 'nav_menu',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'save_format' => 'menu',
			'container' => 'nav',
			'allow_null' => 1,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'side',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
));

endif;

?>