<?php
if( function_exists('register_field_group') ):

register_field_group(array (
	'key' => 'group_54c465090a135',
	'title' => 'Options - Header',
	'fields' => array (
		array (
			'key' => 'field_552607460605a',
			'label' => '1/2',
			'name' => 'half1',
			'prefix' => '',
			'type' => 'column',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'column-type' => '1_2',
		),
		array (
			'key' => 'field_54c4651fc261e',
			'label' => 'Logo (Large)',
			'name' => 'logo_large',
			'prefix' => '',
			'type' => 'image',
			'instructions' => 'For the large version of the site',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => 0,
			'min_height' => 0,
			'min_size' => 0,
			'max_width' => 0,
			'max_height' => 0,
			'max_size' => 0,
			'mime_types' => '',
		),
		array (
			'key' => 'field_552607690605b',
			'label' => '1/2',
			'name' => 'half2',
			'prefix' => '',
			'type' => 'column',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'column-type' => '1_2',
		),
		array (
			'key' => 'field_54c46563c261f',
			'label' => 'Logo (Small)',
			'name' => 'logo_small',
			'prefix' => '',
			'type' => 'image',
			'instructions' => 'For mobile sized screens.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => 0,
			'min_height' => 0,
			'min_size' => 0,
			'max_width' => 0,
			'max_height' => 0,
			'max_size' => 0,
			'mime_types' => '',
		),
		array (
			'key' => 'field_552607830605c',
			'label' => 'Col-end',
			'name' => 'col-end',
			'prefix' => '',
			'type' => 'column',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'column-type' => '1_1',
		),
		array (
			'key' => 'field_55260842a5762',
			'label' => '1/2',
			'name' => 'half3',
			'prefix' => '',
			'type' => 'column',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'column-type' => '1_2',
		),
		array (
			'key' => 'field_5532f7d2d950d',
			'label' => 'Large Logo Positioning: Left',
			'name' => 'logo_left_position',
			'prefix' => '',
			'type' => 'text',
			'instructions' => 'Pixel amount to move left.	Example: -30px for original Tyrex Header Logo.
',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => -30,
			'prepend' => '',
			'append' => 'px',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_5543e1b73cd7e',
			'label' => '1/2',
			'name' => 'half2_copy',
			'prefix' => '',
			'type' => 'column',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'column-type' => '1_2',
		),
		array (
			'key' => 'field_5532f853d950e',
			'label' => 'Large Logo Positioning: Top',
			'name' => 'logo_top_position',
			'prefix' => '',
			'type' => 'text',
			'instructions' => 'Pixel amount to move up.	Example: -30px for original Tyrex Header Logo.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => -30,
			'prepend' => '',
			'append' => 'px',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_55260815a5761',
			'label' => 'col-end2',
			'name' => 'col-end2',
			'prefix' => '',
			'type' => 'column',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'column-type' => '1_1',
		),
		array (
			'key' => 'field_5543e504fb429',
			'label' => '1/2 (copy)',
			'name' => 'half2_copy_copy',
			'prefix' => '',
			'type' => 'column',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'column-type' => '1_2',
		),
		array (
			'key' => 'field_5519755b095b0',
			'label' => 'Menu Type',
			'name' => 'menu_type',
			'prefix' => '',
			'type' => 'select',
			'instructions' => '"Click" would only show the drop down menus when clicked. When changing between "Click" and "Hover" please note that the "Base Page" of the Dropdown will be shown (Hover) or be hidden with (Click).',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'Click' => 'Click',
				'Hover' => 'Hover',
			),
			'default_value' => array (
				'Click' => 'Click',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
		),
		array (
			'key' => 'field_5543e512fb42a',
			'label' => 'Main Menu',
			'name' => 'main_menu',
			'prefix' => '',
			'type' => 'nav_menu',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'save_format' => 'id',
			'container' => 'nav',
			'allow_null' => 0,
		),
		array (
			'key' => 'field_5543e4fffb428',
			'label' => '1/2 (copy)',
			'name' => 'half2_copy_copy',
			'prefix' => '',
			'type' => 'column',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'column-type' => '1_2',
		),
		array (
			'key' => 'field_5543e02230862',
			'label' => 'Show Sub-Nav?',
			'name' => 'show_sub_nav',
			'prefix' => '',
			'type' => 'true_false',
			'instructions' => 'This would be the secondary grey header menu.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
		),
		array (
			'key' => 'field_5543e52cfb42b',
			'label' => 'Sub-Nav',
			'name' => 'sub-nav',
			'prefix' => '',
			'type' => 'nav_menu',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_5543e02230862',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'save_format' => 'id',
			'container' => 'nav',
			'allow_null' => 1,
		),
		array (
			'key' => 'field_5543e4f9fb427',
			'label' => 'col-end2 (copy)',
			'name' => 'col-end2_copy',
			'prefix' => '',
			'type' => 'column',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'column-type' => '1_1',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-header-footer',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
));

endif;
?>