<?php
if( function_exists('register_field_group') ):

register_field_group(array (
	'key' => 'group_54fbe26810dc3',
	'title' => 'Options - Footer',
	'fields' => array (
		array (
			'key' => 'field_550baad88b106',
			'label' => 'Left',
			'name' => '',
			'prefix' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
		),
		array (
			'key' => 'field_552606310aa60',
			'label' => '1/2',
			'name' => 'half1',
			'prefix' => '',
			'type' => 'column',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'column-type' => '1_2',
		),
		array (
			'key' => 'field_552acecb52dd5',
			'label' => 'Logo',
			'name' => '',
			'prefix' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Logo is changed in the "Main Company" area.',
			'esc_html' => 0,
		),
		array (
			'key' => 'field_552606380aa61',
			'label' => '1/2',
			'name' => 'half2',
			'prefix' => '',
			'type' => 'column',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'column-type' => '1_2',
		),
		array (
			'key' => 'field_550bab158b107',
			'label' => 'Privacy Page',
			'name' => 'privacy_page',
			'prefix' => '',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => '',
			'taxonomy' => '',
			'allow_null' => 0,
			'multiple' => 0,
		),
		array (
			'key' => 'field_550bab788b108',
			'label' => 'Terms of Service',
			'name' => 'terms_of_service',
			'prefix' => '',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => '',
			'taxonomy' => '',
			'allow_null' => 0,
			'multiple' => 0,
		),
		array (
			'key' => 'field_552606410aa62',
			'label' => 'end',
			'name' => 'end1',
			'prefix' => '',
			'type' => 'column',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'column-type' => '1_1',
		),
		array (
			'key' => 'field_54fbe577c23a0',
			'label' => 'Middle',
			'name' => '',
			'prefix' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
		),
		array (
			'key' => 'field_552606100aa5e',
			'label' => '1/2',
			'name' => 'half3',
			'prefix' => '',
			'type' => 'column',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'column-type' => '1_2',
		),
		array (
			'key' => 'field_552603f32a101',
			'label' => 'Footer Menu',
			'name' => 'footer_menu',
			'prefix' => '',
			'type' => 'nav_menu',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'save_format' => 'menu',
			'container' => 'nav',
			'allow_null' => 0,
		),
		array (
			'key' => 'field_552606080aa5d',
			'label' => '1/2',
			'name' => 'half4',
			'prefix' => '',
			'type' => 'column',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'column-type' => '1_2',
		),
		array (
			'key' => 'field_550baa264debb',
			'label' => 'Add Newsletter Link?',
			'name' => 'add_newsletter_link',
			'prefix' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
		),
		array (
			'key' => 'field_54fbe58bc23a1',
			'label' => 'Subscribe Page',
			'name' => 'subscribe',
			'prefix' => '',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_550baa264debb',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array (
				0 => 'page',
			),
			'taxonomy' => '',
			'allow_null' => 0,
			'multiple' => 0,
		),
		array (
			'key' => 'field_552605fc0aa5c',
			'label' => 'end',
			'name' => 'end3',
			'prefix' => '',
			'type' => 'column',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'column-type' => '1_1',
		),
		array (
			'key' => 'field_54fbe62dceb08',
			'label' => 'Right',
			'name' => '',
			'prefix' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
		),
		array (
			'key' => 'field_552605740aa59',
			'label' => '1/2',
			'name' => 'half5',
			'prefix' => '',
			'type' => 'column',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'column-type' => '1_2',
		),
		array (
			'key' => 'field_54fbe27dd5224',
			'label' => 'Footer Text Above',
			'name' => 'footer_text_above',
			'prefix' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_54fbe3976c7f7',
			'label' => 'Footer URL',
			'name' => 'footer_url',
			'prefix' => '',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array (
			'key' => 'field_552605b20aa5a',
			'label' => '1/2',
			'name' => 'half6',
			'prefix' => '',
			'type' => 'column',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'column-type' => '1_2',
		),
		array (
			'key' => 'field_54fbe296d5225',
			'label' => 'Footer Image',
			'name' => 'footer_image',
			'prefix' => '',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_552605c20aa5b',
			'label' => 'end col',
			'name' => 'col4',
			'prefix' => '',
			'type' => 'column',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'column-type' => '1_1',
		),
		array (
			'key' => 'field_552b04103d947',
			'label' => 'Logo Bar',
			'name' => '',
			'prefix' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
		),
		array (
			'key' => 'field_552b04383d948',
			'label' => 'Display Footer Logo Bar?',
			'name' => 'display_footer_logo_bar',
			'prefix' => '',
			'type' => 'true_false',
			'instructions' => 'Do you want to display the logo bar in the footer (currently only in iRex)?',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
		),
		array (
			'key' => 'field_5552b8be4eeef',
			'label' => 'Copyright',
			'name' => '',
			'prefix' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
		),
		array (
			'key' => 'field_550dc8b197202',
			'label' => 'Copyright Link',
			'name' => 'copyright_link',
			'prefix' => '',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => '',
			'taxonomy' => '',
			'allow_null' => 0,
			'multiple' => 0,
		),
		array (
			'key' => 'field_54e645b98c839',
			'label' => 'Copyright Text',
			'name' => 'copyright',
			'prefix' => '',
			'type' => 'text',
			'instructions' => 'Full line will read:	
Copyright © 2014 - 2015 by TyRex® Group, Ltd. All rights reserved.
But everything before the "by" is taken care of.
Register mark is		 &r eg;		 (without a space)',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'by TyRex® Group, Ltd. All rights reserved.',
			'placeholder' => '',
			'prepend' => 'Copyright © 2014 - 2015',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-header-footer',
			),
		),
	),
	'menu_order' => 5,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
));

endif;
?>