<?php
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_54de32bf9dcde',
	'title' => 'Options - Sidebar',
	'fields' => array (
		array (
			'key' => 'field_54de3b9388f9e',
			'label' => 'Sidebar Groups',
			'name' => 'sidebar_groups',
			'type' => 'flexible_content',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'button_label' => 'Add Section',
			'min' => '',
			'max' => '',
			'layouts' => array (
				array (
					'key' => '54de3b980d46c',
					'name' => 'download',
					'label' => 'Download',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_54de3bb388f9f',
							'label' => 'Download',
							'name' => 'download',
							'type' => 'post_object',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'post_type' => array (
								0 => 'download',
							),
							'taxonomy' => array (
							),
							'allow_null' => 0,
							'multiple' => 0,
							'return_format' => 'object',
							'ui' => 1,
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '54de3c5288fa4',
					'name' => 'image_link',
					'label' => 'Image lInk',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_54de3c6c88fa5',
							'label' => 'Image',
							'name' => 'image',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => 0,
							'min_height' => 0,
							'min_size' => 0,
							'max_width' => 0,
							'max_height' => 0,
							'max_size' => 0,
							'mime_types' => '',
						),
						array (
							'key' => 'field_54de3c8288fa6',
							'label' => 'Text Below',
							'name' => 'text',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_54de3c9088fa7',
							'label' => 'URL',
							'name' => 'url',
							'type' => 'url',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
						),
						array (
							'key' => 'field_54de3ca788fa8',
							'label' => 'External Link',
							'name' => 'external_link',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '54f2a00581454',
					'name' => 'header',
					'label' => 'Header',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_54f2a01b81455',
							'label' => 'Header',
							'name' => 'header',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '54de3c1a88fa2',
					'name' => 'newsletter',
					'label' => 'Newsletter',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_54de3c3788fa3',
							'label' => 'Newsletter',
							'name' => 'newsletter',
							'type' => 'post_object',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'post_type' => array (
								0 => 'newsletter',
							),
							'taxonomy' => array (
							),
							'allow_null' => 0,
							'multiple' => 0,
							'return_format' => 'object',
							'ui' => 1,
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '54f2a07781456',
					'name' => 'text_links',
					'label' => 'Text Links',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_54f2a17d6434a',
							'label' => 'Text Link Group',
							'name' => 'text_link_group',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'min' => '',
							'max' => '',
							'layout' => 'block',
							'button_label' => 'Add Row',
							'sub_fields' => array (
								array (
									'key' => 'field_54f2a08a81457',
									'label' => 'Text',
									'name' => 'text',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => 33,
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
									'readonly' => 0,
									'disabled' => 0,
								),
								array (
									'key' => 'field_54f2a09a81458',
									'label' => 'Link',
									'name' => 'link',
									'type' => 'url',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => 33,
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
								),
								array (
									'key' => 'field_561337227ad6c',
									'label' => 'External Link?',
									'name' => 'external_link',
									'type' => 'checkbox',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => 33,
										'class' => '',
										'id' => '',
									),
									'choices' => array (
										'External' => 'External',
									),
									'default_value' => array (
									),
									'layout' => 'vertical',
									'toggle' => 0,
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '54f2a46f306c2',
					'name' => 'news_and_events',
					'label' => 'News And Events',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_54f2a486306c3',
							'label' => 'Display Amount',
							'name' => 'display_amount',
							'type' => 'number',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'min' => '',
							'max' => '',
							'step' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_54f2a4c3306c4',
							'label' => 'Types',
							'name' => 'types',
							'type' => 'checkbox',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'articles' => 'Articles',
								'post' => 'News & Events',
							),
							'default_value' => array (
								'posts' => 'News & Events',
							),
							'layout' => 'horizontal',
							'toggle' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '553d88edb1ca5',
					'name' => 'big_button',
					'label' => 'Button',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_553d88ffb1ca6',
							'label' => 'Button Text',
							'name' => 'button_text',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => 50,
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_553d89afb1ca9',
							'label' => 'Linked Page',
							'name' => 'linked_page',
							'type' => 'page_link',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => 50,
								'class' => '',
								'id' => '',
							),
							'post_type' => array (
								0 => 'page',
							),
							'taxonomy' => array (
							),
							'allow_null' => 0,
							'multiple' => 0,
						),
						array (
							'key' => 'field_553d892bb1ca7',
							'label' => 'Text Color',
							'name' => 'text_color',
							'type' => 'color_picker',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => 50,
								'class' => '',
								'id' => '',
							),
							'default_value' => '#fff',
						),
						array (
							'key' => 'field_553d8984b1ca8',
							'label' => 'Background Color',
							'name' => 'background_color',
							'type' => 'color_picker',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => 50,
								'class' => '',
								'id' => '',
							),
							'default_value' => '#900',
						),
					),
					'min' => '',
					'max' => '',
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-sidebar',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif;
?>