<?php
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_54d5355ef3550',
	'title' => 'Sections',
	'fields' => array (
		array (
			'key' => 'field_54d5358ee0330',
			'label' => 'Flexible Content',
			'name' => 'simple_sections',
			'type' => 'flexible_content',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'button_label' => 'Add Section',
			'min' => '',
			'max' => '',
			'layouts' => array (
				array (
					'key' => '54d53591c810b',
					'name' => 'one_column_section',
					'label' => '1 Column Section',
					'display' => 'table',
					'sub_fields' => array (
						array (
							'key' => 'field_54d535b8e0331',
							'label' => 'Column 1',
							'name' => '1_column_1',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '54d536fa19910',
					'name' => 'two_column_section',
					'label' => '2 Column Section',
					'display' => 'table',
					'sub_fields' => array (
						array (
							'key' => 'field_54d5370c19911',
							'label' => 'Column 1',
							'name' => '2_column_1',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
						),
						array (
							'key' => 'field_54d5375a19912',
							'label' => 'Column 2',
							'name' => '2_column_2',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '54d5377619913',
					'name' => 'three_column_section',
					'label' => '3 Column Section',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_54d537b019914',
							'label' => 'Column 1',
							'name' => '3_column_1',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => 33,
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
						),
						array (
							'key' => 'field_54d537cf19915',
							'label' => 'Column 2',
							'name' => '3_column_2',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => 33,
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
						),
						array (
							'key' => 'field_54d537fc19916',
							'label' => 'Column 3',
							'name' => '3_column_3',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => 33,
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
						),
						array (
							'key' => 'field_55318f2bf7a44',
							'label' => '',
							'name' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '54e16fdc59b1e',
					'name' => 'four_column_section',
					'label' => '4 Column Section',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_54e16fdc59b1f',
							'label' => 'Column 1',
							'name' => '4_column_1',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => 50,
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
						),
						array (
							'key' => 'field_54e16fdc59b20',
							'label' => 'Column 2',
							'name' => '4_column_2',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => 50,
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
						),
						array (
							'key' => 'field_54e16fdc59b21',
							'label' => 'Column 3',
							'name' => '4_column_3',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => 50,
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
						),
						array (
							'key' => 'field_54e1700f59b22',
							'label' => 'Column 4',
							'name' => '4_column_4',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => 50,
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '552df4867350a',
					'name' => 'company_table',
					'label' => 'Company Listing',
					'display' => 'row',
					'sub_fields' => array (
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '54d543aba5e8d',
					'name' => 'embed_video',
					'label' => 'Embed Video',
					'display' => 'table',
					'sub_fields' => array (
						array (
							'key' => 'field_54d544de4c0db',
							'label' => 'Video Columns',
							'name' => 'video_columns',
							'type' => 'select',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => 25,
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'one' => 'One Column',
								'two' => 'Two Columns',
								'three' => 'Three Columns',
							),
							'default_value' => array (
								'' => '',
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
							'disabled' => 0,
							'readonly' => 0,
						),
						array (
							'key' => 'field_54d543d7a5e8e',
							'label' => 'Video Group',
							'name' => 'video_group',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => 75,
								'class' => '',
								'id' => '',
							),
							'min' => '',
							'max' => '',
							'layout' => 'row',
							'button_label' => 'Add Video',
							'sub_fields' => array (
								array (
									'key' => 'field_54d5444ba5e90',
									'label' => 'Video',
									'name' => 'video',
									'type' => 'oembed',
									'instructions' => 'Place link to video here. Example: http://www.youtube.com/something',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'width' => '',
									'height' => '',
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '54d538efeb05f',
					'name' => 'full_width_image',
					'label' => 'Full Width Image',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_54d53909eb060',
							'label' => 'Full Image',
							'name' => 'full_image',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => 0,
							'min_height' => 0,
							'min_size' => 0,
							'max_width' => 0,
							'max_height' => 0,
							'max_size' => 0,
							'mime_types' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '54d56b5ae53ba',
					'name' => 'header',
					'label' => 'Header',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_54d56b71e53bb',
							'label' => 'Header',
							'name' => 'header_title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '54d5387b32af7',
					'name' => 'image_gallery',
					'label' => 'Image Gallery',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_54d5389332af8',
							'label' => 'Gallery',
							'name' => 'gallery',
							'type' => 'gallery',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'min' => '',
							'max' => '',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => 0,
							'min_height' => 0,
							'min_size' => 0,
							'max_width' => 0,
							'max_height' => 0,
							'max_size' => 0,
							'mime_types' => '',
						),
						array (
							'key' => 'field_54f2379fbc4f8',
							'label' => 'Add Background',
							'name' => 'add_background',
							'type' => 'checkbox',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'' => '',
							),
							'default_value' => array (
								'' => '',
							),
							'layout' => 'horizontal',
							'toggle' => 0,
						),
						array (
							'key' => 'field_54e173ac59b30',
							'label' => 'Background Color',
							'name' => 'background_color',
							'type' => 'color_picker',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '#fff',
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '54dacf122d231',
					'name' => 'image_grid',
					'label' => 'Image Grid',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_54fdfbb82376b',
							'label' => 'Grid Type',
							'name' => 'grid_type',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => 50,
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'landing' => 'Landing Page',
								'grid' => 'Image Grid',
							),
							'default_value' => array (
								'grid' => 'Image Grid',
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
							'disabled' => 0,
							'readonly' => 0,
						),
						array (
							'key' => 'field_55dc74a06982f',
							'label' => 'Label',
							'name' => 'label',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => 50,
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 0,
						),
						array (
							'key' => 'field_54dacf392d232',
							'label' => 'Image Grid',
							'name' => 'grid_repeater',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'min' => '',
							'max' => '',
							'layout' => 'block',
							'button_label' => 'Add Grid Item',
							'sub_fields' => array (
								array (
									'key' => 'field_54dacfd42d233',
									'label' => 'Image',
									'name' => 'grid_image',
									'type' => 'image',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'array',
									'preview_size' => 'thumbnail',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
								),
								array (
									'key' => 'field_54efd15874a08',
									'label' => 'Add A Link?',
									'name' => 'grid_link',
									'type' => 'select',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => 50,
										'class' => '',
										'id' => '',
									),
									'choices' => array (
										'none' => 'None',
										'anchor' => 'Anchor',
										'URL' => 'Outside Link',
										'page' => 'Page',
										'pdf' => 'PDF',
									),
									'default_value' => array (
									),
									'allow_null' => 0,
									'multiple' => 0,
									'ui' => 0,
									'ajax' => 0,
									'placeholder' => '',
									'disabled' => 0,
									'readonly' => 0,
								),
								array (
									'key' => 'field_54dad00a2d234',
									'label' => 'URL',
									'name' => 'grid_url',
									'type' => 'url',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array (
										array (
											array (
												'field' => 'field_54efd15874a08',
												'operator' => '==',
												'value' => 'URL',
											),
										),
									),
									'wrapper' => array (
										'width' => 50,
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
								),
								array (
									'key' => 'field_54efe9e4c0256',
									'label' => 'Override Item\'s Text',
									'name' => 'grid_text',
									'type' => 'text',
									'instructions' => 'If left blank, the file name, url or page\'s name will display.	This field will override that text.',
									'required' => 0,
									'conditional_logic' => array (
										array (
											array (
												'field' => 'field_55dc74a06982f',
												'operator' => '==',
												'value' => '1',
											),
										),
									),
									'wrapper' => array (
										'width' => 50,
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
									'readonly' => 0,
									'disabled' => 0,
								),
								array (
									'key' => 'field_54efe52ab785c',
									'label' => 'Page',
									'name' => 'grid_page',
									'type' => 'post_object',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array (
										array (
											array (
												'field' => 'field_54efd15874a08',
												'operator' => '==',
												'value' => 'page',
											),
										),
										array (
											array (
												'field' => 'field_54efd15874a08',
												'operator' => '==',
												'value' => 'anchor',
											),
										),
									),
									'wrapper' => array (
										'width' => 50,
										'class' => '',
										'id' => '',
									),
									'post_type' => array (
										0 => 'page',
									),
									'taxonomy' => array (
									),
									'allow_null' => 0,
									'multiple' => 0,
									'return_format' => 'object',
									'ui' => 1,
								),
								array (
									'key' => 'field_54efd39574a09',
									'label' => 'Anchor',
									'name' => 'grid_anchor',
									'type' => 'post_object',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array (
										array (
											array (
												'field' => 'field_54efd15874a08',
												'operator' => '==',
												'value' => 'anchor',
											),
										),
									),
									'wrapper' => array (
										'width' => 50,
										'class' => '',
										'id' => '',
									),
									'post_type' => array (
										0 => 'panel',
									),
									'taxonomy' => array (
									),
									'allow_null' => 0,
									'multiple' => 0,
									'return_format' => 'object',
									'ui' => 1,
								),
								array (
									'key' => 'field_54efd45274a0a',
									'label' => 'PDF',
									'name' => 'grid_pdf',
									'type' => 'file',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array (
										array (
											array (
												'field' => 'field_54efd15874a08',
												'operator' => '==',
												'value' => 'pdf',
											),
										),
									),
									'wrapper' => array (
										'width' => 50,
										'class' => '',
										'id' => '',
									),
									'return_format' => 'array',
									'library' => 'all',
									'min_size' => '',
									'max_size' => '',
									'mime_types' => '',
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '54d5392feb061',
					'name' => 'mini_slideshow',
					'label' => 'Mini Slideshow',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_54d5393ceb062',
							'label' => 'Slideshow Group',
							'name' => 'slideshow_group',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'min' => '',
							'max' => '',
							'layout' => 'row',
							'button_label' => 'Add Image',
							'sub_fields' => array (
								array (
									'key' => 'field_54d5395feb063',
									'label' => 'Image',
									'name' => 'slideshow_image',
									'type' => 'image',
									'instructions' => '*Required',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'array',
									'preview_size' => 'thumbnail',
									'library' => 'all',
									'min_width' => 0,
									'min_height' => 0,
									'min_size' => 0,
									'max_width' => 0,
									'max_height' => 0,
									'max_size' => 0,
									'mime_types' => '',
								),
								array (
									'key' => 'field_54d5397ceb064',
									'label' => 'Image Title',
									'name' => 'image_title',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
									'readonly' => 0,
									'disabled' => 0,
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '54d56d9f9ea45',
					'name' => 'panel_row',
					'label' => 'Panel',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_54d56dbf9ea46',
							'label' => 'Panel Selector',
							'name' => 'panel_selector',
							'type' => 'post_object',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'post_type' => array (
								0 => 'panel',
							),
							'taxonomy' => array (
							),
							'allow_null' => 0,
							'multiple' => 0,
							'return_format' => 'object',
							'ui' => 1,
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '54ebe447ca812',
					'name' => 'download_list',
					'label' => 'Download List',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_54ebe573ca814',
							'label' => 'Downloads',
							'name' => 'downloads_list',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'min' => '',
							'max' => '',
							'layout' => 'block',
							'button_label' => 'Add Download',
							'sub_fields' => array (
								array (
									'key' => 'field_54ebe5a0ca815',
									'label' => 'Download',
									'name' => 'download',
									'type' => 'file',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'array',
									'library' => 'all',
									'min_size' => 0,
									'max_size' => 0,
									'mime_types' => '',
								),
								array (
									'key' => 'field_54ebe5d2ca816',
									'label' => 'Text',
									'name' => 'text_replace',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
									'readonly' => 0,
									'disabled' => 0,
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '54ebf3e04b9f2',
					'name' => 'download_buttons',
					'label' => 'Download Buttons',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_54ebf49d4b9f3',
							'label' => 'Downloads',
							'name' => 'downloads_list',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'min' => '',
							'max' => '',
							'layout' => 'table',
							'button_label' => 'Add Row',
							'sub_fields' => array (
								array (
									'key' => 'field_54ebf4bf4b9f4',
									'label' => 'Download',
									'name' => 'download',
									'type' => 'file',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'array',
									'library' => 'all',
									'min_size' => 0,
									'max_size' => 0,
									'mime_types' => '',
								),
								array (
									'key' => 'field_54ebf4e94b9f5',
									'label' => 'Text',
									'name' => 'text_replace',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
									'readonly' => 0,
									'disabled' => 0,
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
		),
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'article',
			),
		),
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'press-releases',
			),
		),
		array (
			array (
				'param' => 'page_type',
				'operator' => '==',
				'value' => 'front_page',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif;
?>