<?php 
$conditions_arr = array(
		'connector' => array(
				'1' => array('sc upc' => 'blue', 'sc apc' => 'green', 'lc upc' => 'blue', 'lc apc' => 'green'),								
				'2' => array('sc upc' => 'blue', 'sc apc' => 'green', 'lc upc' => 'blue', 'lc apc' => 'green'),
				'3' => array('sc upc' => 'beige', 'lc upc' => 'beige'),
				'4' => array('sc upc' => 'beige', 'lc upc' => 'beige'),
				'5' => array('sc upc' => 'beige', 'lc upc' => 'beige')
			),	
		'boot' => array(
				'3' => array('white'),
				'4' => array('blue')
			),
		'cable' => array(
				'116' => array('cable' => 'yellow'),
				'117' => array('cable' => 'yellow'),
				'123' => array('cable' => 'yellow'),
				'120'	=> array('cable' => 'yellow'),
				'115'	=> array('cable' => 'yellow'),
				'118'	=> array('cable' => 'yellow'),
				'119'	=> array('cable' => 'yellow'),
				'121'	=> array('cable' => 'black'),								
				'105'	=> array('cable' => 'black'),
				'216' => array('cable' => 'yellow'),
				'217' => array('cable' => 'yellow'),
				'223' => array('cable' => 'yellow'),
				'220' => array('cable' => 'yellow'),
				'215' => array('cable' => 'yellow'),
				'218' => array('cable' => 'yellow'),
				'219' => array('cable' => 'yellow'),
				'221' => array('cable' => 'black'),								
				'205' => array('cable' => 'black'),
				'316' => array('cable' => 'orange'),
				'317' => array('cable' => 'orange'),
				'323' => array('cable' => 'orange'),
				'320' => array('cable' => 'orange'),
				'315' => array('cable' => 'orange'),
				'318' => array('cable' => 'orange'),
				'319' => array('cable' => 'orange'),
				'321' => array('cable' => 'black'),
				'306' => array('cable' => 'black'),
				'307' => array('cable' => 'black'),
				'305' => array('cable' => 'black'),
				'416' => array('cable' => 'aqua'),
				'417' => array('cable' => 'aqua'),
				'423' => array('cable' => 'aqua'),
				'420' => array('cable' => 'aqua'),
				'415' => array('cable' => 'aqua'),
				'418' => array('cable' => 'aqua'),
				'419' => array('cable' => 'aqua'),
				'421' => array('cable' => 'black'),
				'406' => array('cable' => 'black'),
				'407' => array('cable' => 'black'),
				'405' => array('cable' => 'black'),
				'516' => array('cable' => 'aqua'),
				'517' => array('cable' => 'aqua'),
				'523' => array('cable' => 'aqua'),
				'520' => array('cable' => 'aqua'),
				'515' => array('cable' => 'aqua'),
				'518' => array('cable' => 'aqua'),
				'519' => array('cable' => 'black'),
				'521' => array('cable' => 'black'),
				'506' => array('cable' => 'black'),
				'507' => array('cable' => 'black'),
				'505' => array('cable' => 'black'),
				'124' => array('cable' => 'yellow', 'fanout' => 'yellow'),
				'122' => array('cable' => 'yellow', 'fanout' => 'yellow'),				
				'112' => array('cable' => 'black', 'fanout' => 'yellow'),
				'127'	=> array('cable' => 'black', 'fanout' =>'multi'),
				'134'	=> array('cable' => 'black', 'fanout' =>'multi'),
				'109'	=> array('cable' => 'black', 'fanout' =>'multi'),
				'224'	=> array('cable' => 'yellow', 'fanout' =>'yellow'),
				'222'	=> array('cable' => 'yellow', 'fanout' =>'yellow'),				
				'212'	=> array('cable' => 'black', 'fanout' =>'yellow'),
				'227'	=> array('cable' => 'black', 'fanout' =>'multi'),
				'234'	=> array('cable' => 'black', 'fanout' =>'multi'),
				'209'	=> array('cable' => 'black', 'fanout' =>'multi'),
				'324'	=> array('cable' => 'orange', 'fanout' =>'orange'),
				'322'	=> array('cable' => 'orange', 'fanout' =>'orange'),				
				'312'	=> array('cable' => 'black', 'fanout' =>'orange'),
				'327'	=> array('cable' => 'black', 'fanout' =>'multi'),
				'334'	=> array('cable' => 'black', 'fanout' =>'multi'),
				'309'	=> array('cable' => 'black', 'fanout' =>'multi'),
				'424'	=> array('cable' => 'aqua', 'fanout' =>'aqua'),
				'422'	=> array('cable' => 'aqua', 'fanout' =>'aqua'),				
				'412'	=> array('cable' => 'aqua', 'fanout' =>'aqua'),
				'427'	=> array('cable' => 'black', 'fanout' =>'multi'),
				'434'	=> array('cable' => 'black', 'fanout' =>'multi'),
				'409'	=> array('cable' => 'black', 'fanout' =>'multi'),
				'524'	=> array('cable' => 'aqua', 'fanout' =>'aqua'),
				'522'	=> array('cable' => 'aqua', 'fanout' =>'aqua'),				
				'512'	=> array('cable' => 'aqua', 'fanout' =>'aqua'),
				'527'	=> array('cable' => 'black', 'fanout' =>'multi'),
				'534'	=> array('cable' => 'black', 'fanout' =>'multi'),
				'509'	=> array('cable' => 'black', 'fanout' =>'multi'),
				'126' => array('cable' => 'yellow', 'fanout' => 'yellow'),
				'125' => array('cable' => 'black', 'fanout' => 'yellow'),
				'114' => array('cable' => 'black', 'fanout' => 'multi'),
				'113' => array('cable' => 'yellow', 'fanout' => 'multi'),
				'111' => array('cable' => 'black', 'fanout' => 'yellow'),
				'131' => array('cable' => 'black', 'fanout' => 'yellow'),
				'132' => array('cable' => 'black', 'fanout' => 'yellow'),
				'226' => array('cable' => 'yellow', 'fanout' => 'yellow'),
				'225' => array('cable' => 'black', 'fanout' => 'yellow'),
				'214' => array('cable' => 'black', 'fanout' => 'multi'),
				'213' => array('cable' => 'yellow', 'fanout' => 'multi'),
				'211' => array('cable' => 'black', 'fanout' => 'yellow'),				
				'232' => array('cable' => 'black', 'fanout' => 'yellow'),
				'326' => array('cable' => 'orange', 'fanout' => 'orange'),
				'325' => array('cable' => 'black', 'fanout' => 'orange'),
				'314' => array('cable' => 'black', 'fanout' => 'multi'),
				'313' => array('cable' => 'orange', 'fanout' => 'multi'),
				'311' => array('cable' => 'black', 'fanout' => 'orange'),				
				'332' => array('cable' => 'black', 'fanout' => 'orange'),
				'426' => array('cable' => 'aqua', 'fanout' => 'aqua'),
				'425' => array('cable' => 'black', 'fanout' => 'aqua'),
				'414' => array('cable' => 'black', 'fanout' => 'multi'),
				'413' => array('cable' => 'aqua', 'fanout' => 'multi'),
				'411' => array('cable' => 'black', 'fanout' => 'aqua'),
				'431' => array('cable' => 'black', 'fanout' => 'aqua'),				
				'526' => array('cable' => 'aqua', 'fanout' => 'aqua'),
				'525' => array('cable' => 'black', 'fanout' => 'aqua'),
				'514' => array('cable' => 'black', 'fanout' => 'multi'),
				'513' => array('cable' => 'aqua', 'fanout' => 'multi'),
				'511' => array('cable' => 'black', 'fanout' => 'aqua'),
				'531' => array('cable' => 'black', 'fanout' => 'aqua'),				
				'104' => array('cable' => 'black', 'fanout' => 'multi'),
				'103' => array('cable' => 'black', 'fanout' => 'multi'),
				'102' => array('cable' => 'black', 'fanout' => 'multi'),
				'110' => array('cable' => 'black', 'fanout' => 'yellow'),
				'108' => array('cable' => 'black', 'fanout' => 'yellow'),
				'131' => array('cable' => 'black', 'fanout' => 'multi'),
				'135' => array('cable' => 'black', 'fanout' => 'multi'),
				'132' => array('cable' => 'black', 'fanout' => 'multi'),
				'128' => array('cable' => 'black', 'fanout' => 'multi'),
				'130' => array('cable' => 'black', 'fanout' => 'multi'),
				'204' => array('cable' => 'black', 'fanout' => 'multi'),
				'203' => array('cable' => 'black', 'fanout' => 'multi'),
				'202' => array('cable' => 'black', 'fanout' => 'multi'),
				'210' => array('cable' => 'black', 'fanout' => 'multi'),
				'208' => array('cable' => 'black', 'fanout' => 'yellow'),
				'231' => array('cable' => 'black', 'fanout' => 'yellow'),
				'235' => array('cable' => 'black', 'fanout' => 'multi'),
				'232' => array('cable' => 'black', 'fanout' => 'multi'),
				'228' => array('cable' => 'black', 'fanout' => 'multi'),
				'230' => array('cable' => 'black', 'fanout' => 'multi'),
				'304' => array('cable' => 'black', 'fanout' => 'multi'),
				'303' => array('cable' => 'black', 'fanout' => 'multi'),
				'302' => array('cable' => 'black', 'fanout' => 'multi'),
				'310' => array('cable' => 'black', 'fanout' => 'multi'),
				'308' => array('cable' => 'black', 'fanout' => 'multi'),
				'331' => array('cable' => 'black', 'fanout' => 'orange'),
				'335' => array('cable' => 'black', 'fanout' => 'orange'),
				'332' => array('cable' => 'black', 'fanout' => 'multi'),
				'328' => array('cable' => 'black', 'fanout' => 'multi'),
				'330' => array('cable' => 'black', 'fanout' => 'multi'),
				'404' => array('cable' => 'black', 'fanout' => 'multi'),
				'403' => array('cable' => 'black', 'fanout' => 'multi'),
				'402' => array('cable' => 'black', 'fanout' => 'multi'),
				'410' => array('cable' => 'black', 'fanout' => 'multi'),
				'408' => array('cable' => 'black', 'fanout' => 'multi'),
				'431' => array('cable' => 'black', 'fanout' => 'multi'),
				'435' => array('cable' => 'black', 'fanout' => 'aqua'),
				'432' => array('cable' => 'black', 'fanout' => 'aqua'),
				'428' => array('cable' => 'black', 'fanout' => 'multi'),
				'430' => array('cable' => 'black', 'fanout' => 'multi'),
				'504' => array('cable' => 'black', 'fanout' => 'multi'),
				'503' => array('cable' => 'black', 'fanout' => 'multi'),
				'502' => array('cable' => 'black', 'fanout' => 'multi'),
				'510' => array('cable' => 'black', 'fanout' => 'multi'),
				'508' => array('cable' => 'black', 'fanout' => 'multi'),
				'531' => array('cable' => 'black', 'fanout' => 'multi'),
				'535' => array('cable' => 'black', 'fanout' => 'multi'),
				'532' => array('cable' => 'black', 'fanout' => 'aqua'),
				'528' => array('cable' => 'black', 'fanout' => 'aqua'),
				'530' => array('cable' => 'black', 'fanout' => 'multi'),
				'101' => array('cable' => 'black', 'fanout' => 'yellow'),
				'106' => array('cable' => 'black', 'fanout' => 'yellow'),
				'107' => array('cable' => 'black', 'fanout' => 'yellow'),
				'129' => array('cable' => 'black', 'fanout' => 'yellow'),
				'133' => array('cable' => 'black', 'fanout' => 'yellow'),
				'201' => array('cable' => 'black', 'fanout' => 'yellow'),
				'206' => array('cable' => 'black', 'fanout' => 'yellow'),
				'207' => array('cable' => 'black', 'fanout' => 'yellow'),
				'229' => array('cable' => 'black', 'fanout' => 'yellow'),
				'233' => array('cable' => 'black', 'fanout' => 'yellow')
			)		
	);
?>